### ISSUE TITLE
Crawler should not die on error

### ISSUE THREAD

**Issue by frisitano** [reef-defi/reef-explorer#115]
We should make modifications to the crawler logic such that if an exception is raised during the processing of a block then the block should be skipped an error messaged raised in sentry.  We would then address the root cause and replay the skipped block with new business logic.

**Comment by Netherdrake** [comment]
For data consistency sake, perhaps it can die on error, but at least it should have a detailed log+stacktrace of the event recorded in Sentry.

**Comment by frisitano** [comment]
> For data consistency sake, perhaps it can die on error, but at least it should have a detailed log+stacktrace of the event recorded in Sentry.

Perhaps but then the crawler will be offline completely until a dev is able to deploy a fix.  My concern is that we run the risk of not having a dev available to develop and deploy a solution quickly.

**Comment by Netherdrake** [comment]
For all crashes except faulty logic it gets auto-restarted anyway.

**Comment by frisitano** [comment]
Yeah it's unrecoverable errors / exceptions that I'm concerned about.  In those situations I think maintaining some level of service is preferable to the crawler going down and no new blocks being parsed.  If you think it's best to stop completely then we can just leave as is and see how things perform moving forward.

**Comment by Netherdrake** [comment]
Unrecoverable error means something bad happened (chain issue, db issue or core library bug), so its probably safest to stop.

**Comment by frisitano** [comment]
cool, will close the issue.
