### ISSUE TITLE
Frontend bugs

### ISSUE THREAD

**Issue by matjazonline** [reef-defi/reef-explorer#135]
- [x] check verify form in: reefscan, remix, hardhat
- [x] homepage search box should support evm addresses (accounts & contracts)
- [x] remove "PolkaStats", "PolkaStats NG"
- [ ] https://testnet.reefscan.com/contract/0x913208decfaf8829e81d1b1c12dc4037786f5b8d
- [x] add header block time to the Chain.vue
- [x] display accounts by EVM address https://testnet.reefscan.com/account/0x32e7509e5ad5c4ac47bdbfe2e237890c63df8214
- [x] preloader for extrinsic Triggered Events
- [ ] fix ./components/ContractCallFunctionWrite.vue https://github.com/reef-defi/reef-explorer/security/dependabot
- [x]  contracts list item token link reloads whole page
- [x] display transfers under token and transactions under contracts
- [x] display ~0.00 on list and full decimals in detail view
- [x] fix undefined value error https://testnet.reefscan.com/contract/tx/0x2ef8089c09f4ba2892098ba4bf201052563a57e2a67241dd1f2bd123029941a8
- [x] display checksum case addresses
https://testnet.reefscan.com/contract/0xBC26364D2b3b94BeE7f3ce38799b0Ab3Fb1773A4

**Comment by Netherdrake** [comment]
~Also the router is still broken for checksum case addresses:
https://testnet.reefscan.com/contract/0xBC26364D2b3b94BeE7f3ce38799b0Ab3Fb1773A4~

**Comment by Netherdrake** [comment]
A few more issues:
- [ ] The contract page is missing the transactions tab (all recent transactions related to the contract)

- [x] The tokens page should have developer tab removed (its totally irrelevant to the token)
- [ ] The token tracker shows all accounts as token holders (https://testnet.reefscan.com/tokens). It should only show accounts that actually have tokens as token holders. Same goes for holders tab on tokens page.
- [x] Bytecode and constructor arguments on https://testnet.reefscan.com/contract/0xa53346a8438be1a73787d9b78c0e64f047669673 should be moved into developer tab to make the main page cleaner

**Comment by Netherdrake** [comment]
The events page is broken https://testnet.reefscan.com/event/2129473/0/0
