### ISSUE TITLE
Database schema refactor

### ISSUE THREAD

**Issue by mariopino** [reef-defi/reef-explorer#18]
- Use foreign keys relations
- Double check indexes
- Add support for storing parsed contract call arguments
- Add new fields for contract table:
  - `token_trusted`
  - `token_description`
  - `token_icon`
  - `token_coingecko_ticker`
  - `token_coinmarketcap_ticker`

**Comment by Netherdrake** [comment]
Having the tokens and contracts columns in a shared table makes the table a bit inefficient and possibly messy when we add identities for other token/nft/contract types. I'm not sure if its to make graphql queries easier, but traditionally one might want to have separate table for tokens and then link the `contracts` and `tokens` tables via foreign key relationship. The shared view can be then quickly and efficiently recreated using the JOIN query.
