### ISSUE TITLE
Contract is not visible in Testnet reefscan

### ISSUE THREAD

**Issue by anon-mirror** [reef-defi/reef-explorer#259]
I created a contract in Testnet using Remix Reef IDE, according to first workshop (simple ERC20 token).
The contract is not visible on reefscan site, although I can interact with it using Remix

Contract address: https://testnet.reefscan.com/contract/0xc3F4E9390B76Ea6BffAAFCdEcb495c5dC4223Fb0

**Comment by anon-mirror** [comment]
Update: after 2 days contract appeared in reefscan.
I noticed similar issue with the mainnet: my balance and rewards were not displayed up-to-dated, although in reef browser extension and reef console the balance was correct.

**Comment by Netherdrake** [comment]
Testnet explorer was offline, not a bug per se.
