### ISSUE TITLE
Rewards aren't being listed correcly

### ISSUE THREAD

**Issue by RomuloSiebra** [reef-defi/reef-explorer#48]
Since the node update to REEF v4.0.0 rewards aren't being listed on the explorer frontend, for instance, lets get the block with numbe 1,435,646 which has a payoutStakers extrinsic:

![image](https://user-images.githubusercontent.com/51921927/140417111-2b26a958-b39a-4664-b0b1-c0294e6f2c3b.png)
ref: https://console.reefscan.com/#/explorer/query/0xe38fb14ec0d09874e3ef48a1ea97f763ee2e57291400a6a0884ccac03c4526e3

if you check in reefscan the newer reward listed by the first payout address, which in this case is `5DHgDZwvqFjFVHeyx1f4MH2ASq3eZ6NBkuENezPmQxo1YvLS`, only shows a reward received before the update:

![image](https://user-images.githubusercontent.com/51921927/140417721-6cdf40f9-227a-4b3b-8dfb-ba0737a1f75e.png)
ref: https://reefscan.com/account/5DHgDZwvqFjFVHeyx1f4MH2ASq3eZ6NBkuENezPmQxo1YvLS

I noticed that the event method changed from `Reward` to `Rewarded`, so I think this could be the culprit for this issue

**Comment by mariopino** [comment]
Thanks for reporting @RomuloSiebra, fixed by #50 and will be deployed ASAP.
